<?php

/**
 * PluginsfiCalEventTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginsfiCalEventTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return PluginsfiCalEventTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginsfiCalEvent');
    }
}