<?php

/**
 * PluginsfiCalRecurrenceTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginsfiCalRecurrenceTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return PluginsfiCalRecurrenceTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginsfiCalRecurrence');
    }
}