<?php

/**
 * PluginsfiCalCalendarTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginsfiCalCalendarTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginsfiCalCalendarTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginsfiCalCalendar');
    }
}