sfiCalEvent:
  actAs:
    Timestampable: ~
  columns:
    description: string(255)
    location: string
    summary: string
    status:
      type: enum
      values: [ 'tentative', 'confirmed', 'cancelled' ]
    classification:
      type: enum
      values: [ 'public', 'private', 'confidential' ]
      default: 'public'
    priority:
      type: integer(3)
      range: [0, 9]
    all_day:
      type: boolean
      default: false
    start_date: timestamp
    end_date: timestamp
    recurrence_id: integer
    #@TODO Should this be done differently
    exception_dates: array
    original_date: timestamp
  relations:

sfiCalRecurrence:
  columns:
    bydaydays:
      type: array
    bydayfreq:
      type: array
    bymonth:
      type: array
    bymonthday:
      type: array
    bysetpos:
      type: array
    byweeknumber:
      type: array
    byyearday:
      type: array
    byyearday:
      type: array
    count:
      type: integer
    frequency:
      type: enum
      values: [ 'daily', 'weekly', 'monthly', 'yearly' ]
    frequency_interval:
      type: integer
    until:
      type: date
    weekstartday:
      type: enum
      values: [ 'sunday', 'monday', 'tuesday', 'wednesday', 'thursday', 'friday', 'saturday' ]
  relations:
    Event:
      class: sfiCalEvent
      local: id
      type: one
      foreign: recurrence_id
      foreignType: one
      foreignAlias: Recurrence
