sfiCalCalendar:
  columns:
    title: string(255)
    notes: string

sfiCalEvent:
  actAs:
    Timestampable: ~
  columns:
    calendar_id: integer
    description: string(255)
    location: string
    summary: string
    status:
      type: enum
      values: [ 'tentative', 'confirmed', 'cancelled' ]
      default: 'confirmed'
    classification:
      type: enum
      values: [ 'public', 'private', 'confidential' ]
      default: 'public'
    priority:
      type: integer(3)
      range: [0, 9]
    all_day:
      type: boolean
      default: false
    start_date: timestamp
    end_date: timestamp
    recurrence_id: integer
    #@TODO Should this be done differently
    exception_dates: array
    original_date: timestamp
  relations:
    Calendar:
      class: sfiCalCalendar
      local: calendar_id
      foreign: id
      type: one
      foreignType: many
      foreignAlias: Events
      onDelete: CASCADE

sfiCalRecurrence:
  columns:
    bydaydays:
      type: array
#      Arrayvalues: [ sunday, monday, tuesday, wednesday, thursday, friday, saturday ]
    bydayfreq:
      type: array
#      Arrayvalues: [ sunday, monday, tuesday, wednesday, thursday, friday, saturday]
    bymonth:
      type: array
#       Arrayrange: [1, 12]
    bymonthday:
      type: array
    bysetpos:
      type: array
    byweeknumber:
      type: array
    byyearday:
      type: array
    byyearday:
      type: array
    count:
      type: integer
    frequency:
      type: enum
      values: [ 'daily', 'weekly', 'monthly', 'yearly' ]
      notnull: true
      notblank: true
    frequency_interval:
      type: integer
    until:
      type: date
    weekstartday:
      type: enum
      values: [ 'sunday', 'monday', 'tuesday', 'wednesday', 'thursday', 'friday', 'saturday' ]
  relations:
    Event:
      class: sfiCalEvent
      local: id
      type: one
      foreign: recurrence_id
      foreignType: one
      foreignAlias: Recurrence
      onDelete: CASCADE
